### ISSUE TITLE
Finish the game!

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s2-evaluacion-intermedia-emma-martin#1]
Really cool job @emma-martin  !!!

Here you have some tips to finish the game:

- [x] Remove unused files/folders from the project: assets/icons, assets/images...
- [x] A form element would help the user to send the input when clicking the enter key.
- [x] If you generate and save the random number every time the user clicks the button, it changes!! That makes the game too difficult and the clues have no sense. Let's move that logic outside the click handler to generate the random number only once when the page loads
- [x] Remember to convert input value string to a number
- [x] Define the logic to make the counter work
- [ ] Extract the feedback painter to a function
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Do not call undefined functions (HowManyTries).

Let me know if you have any doubts ;)

Go for it!!

**Comment by emma-martin** [comment]
Hi, @nasivuela ! Thanks so much for your time and input. 

Please kindly review the exercise with checks #2, 3, 4, 5, 7 & 8 addressed. Not sure about checks # 1 & 6, though, could you please explain them further for me?

On a side note, I'll work on another branch, titled "Games expansion" to prepare a little game for my godchildren during Xmas :-D

**Comment by nasivuela** [comment]
Well done @emma !!

I have erased the first point, my fault.
About 6: you are writing many times `answersBox.innerHTML = 'something'`, so you can move it to a function ;)

Also, when I said to avoid extra white spaces I didn't mean you should not have white spaces at all, usually we use them to separate concepts and increase readability, but only once at the time.

Feel free to make you Xmas game directly on master ;)

![](https://media.giphy.com/media/26tPcgtbhhbU88U2A/giphy.gif)
